# Generated by Django 5.0.3 on 2024-03-09 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusEcho', '0002_faculty_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(choices=[('Medicine', 'Medicine'), ('Engineering', 'Engineering'), ('Media', 'Media'), ('Computing', 'Computing'), ('Business', 'Business'), ('Science and Technology', 'Science and Technology'), ('TVET', 'TVET')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Phone number must be in the format: '+1234567890'. Up to 15 digits allowed.", max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+1234567890'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
