# Generated by Django 5.0.3 on 2024-03-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusEcho', '0004_alter_profile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='faculty',
            field=models.CharField(blank=True, choices=[('Medicine', 'Medicine'), ('Engineering', 'Engineering'), ('Media', 'Media'), ('Computing', 'Computing'), ('Business', 'Business'), ('Science and Technology', 'Science and Technology'), ('TVET', 'TVET')], default='other', max_length=100),
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
