# Generated by Django 5.0.3 on 2024-03-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusEcho', '0005_alter_profile_faculty_delete_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('academics', 'Academics'), ('finance', 'Finance'), ('health', 'Health and Welfare'), ('housing', 'Housing'), ('other', 'Other')], max_length=100)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('urgent', 'Urgent'), ('emergency', 'Emergency'), ('normal', 'Normal')], max_length=100)),
                ('feedback_type', models.CharField(choices=[('complaint', 'Complaint'), ('recommendation', 'Recommendation'), ('report', 'Report'), ('other', 'Other')], max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='feedback_evidence/')),
                ('status', models.CharField(choices=[('resolved', 'Resolved'), ('pending', 'Pending')], default='pending', max_length=100)),
            ],
        ),
    ]
