# Generated by Django 5.0.3 on 2024-03-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusEcho', '0006_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('administrator', 'Administrator')], max_length=30),
        ),
    ]
