# Generated by Django 5.0.3 on 2024-03-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusEcho', '0009_alter_feedback_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
