# Generated by Django 5.0.3 on 2024-03-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusEcho', '0012_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
