# Generated by Django 5.0.3 on 2024-03-13 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusEcho', '0015_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='student_phone_number',
            field=models.CharField(blank=True, help_text="Phone number must be in the format: '+1234567890'. Up to 15 digits allowed.", max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+1234567890'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
